# コート2面、プレイヤー16人
sequence1:
  coat1:
    home: [1]
    away: [2]
  coat2:
    home: [3]
    away: [4]
sequence2:
  coat1:
    home: [5]
    away: [6]
  coat2:
    home: [7]
    away: [8]
sequence3:
  coat1:
    home: [9]
    away: [10]
  coat2:
    home: [11]
    away: [12]
sequence4:
  coat1:
    home: [13]
    away: [14]
  coat2:
    home: [15]
    away: [16]
sequence5:
  coat1:
    home: [1]
    away: [3]
  coat2:
    home: [2]
    away: [4]
sequence6:
  coat1:
    home: [5]
    away: [7]
  coat2:
    home: [6]
    away: [8]
sequence7:
  coat1:
    home: [9]
    away: [11]
  coat2:
    home: [10]
    away: [12]
sequence8:
  coat1:
    home: [13]
    away: [15]
  coat2:
    home: [14]
    away: [16]
sequence9:
  coat1:
    home: [1]
    away: [4]
  coat2:
    home: [2]
    away: [3]
sequence10:
  coat1:
    home: [5]
    away: [8]
  coat2:
    home: [6]
    away: [7]
sequence11:
  coat1:
    home: [9]
    away: [12]
  coat2:
    home: [10]
    away: [11]
sequence12:
  coat1:
    home: [13]
    away: [16]
  coat2:
    home: [14]
    away: [15]
sequence13:
  coat1:
    home: [1]
    away: [5]
  coat2:
    home: [2]
    away: [6]
sequence14:
  coat1:
    home: [3]
    away: [7]
  coat2:
    home: [4]
    away: [8]
sequence15:
  coat1:
    home: [9]
    away: [13]
  coat2:
    home: [10]
    away: [14]
sequence16:
  coat1:
    home: [11]
    away: [15]
  coat2:
    home: [12]
    away: [16]
sequence17:
  coat1:
    home: [1]
    away: [6]
  coat2:
    home: [2]
    away: [5]
sequence18:
  coat1:
    home: [3]
    away: [8]
  coat2:
    home: [4]
    away: [7]
sequence19:
  coat1:
    home: [9]
    away: [14]
  coat2:
    home: [10]
    away: [13]
sequence20:
  coat1:
    home: [11]
    away: [16]
  coat2:
    home: [12]
    away: [15]
sequence21:
  coat1:
    home: [1]
    away: [7]
  coat2:
    home: [2]
    away: [8]
sequence22:
  coat1:
    home: [5]
    away: [3]
  coat2:
    home: [6]
    away: [4]
sequence23:
  coat1:
    home: [9]
    away: [15]
  coat2:
    home: [10]
    away: [16]
sequence24:
  coat1:
    home: [13]
    away: [11]
  coat2:
    home: [14]
    away: [12]
sequence25:
  coat1:
    home: [1]
    away: [8]
  coat2:
    home: [2]
    away: [7]
sequence26:
  coat1:
    home: [3]
    away: [6]
  coat2:
    home: [4]
    away: [5]
sequence27:
  coat1:
    home: [9]
    away: [16]
  coat2:
    home: [10]
    away: [15]
sequence28:
  coat1:
    home: [11]
    away: [14]
  coat2:
    home: [12]
    away: [13]
sequence29:
  coat1:
    home: [1]
    away: [9]
  coat2:
    home: [2]
    away: [10]
sequence30:
  coat1:
    home: [7]
    away: [15]
  coat2:
    home: [8]
    away: [16]
